### PR TITLE
Updated OpenCore from 0.8.9 to 0.9.1

### PR DESCRIPTION
**Pull request by mandresve**
The commits were made to ensure OpenCore update from 0.8.9 to 0.9.1 without breaking anything. Updated Kexts accordingly to the latest versions. Added support for CPUFriend (but not provide default CPUFriendData) and support for Voltageshift. I Tested this under S540 / XIaoXinAir14 machines for over a week using Ventura. No problems so far.

### CODE REVIEW

**Comment by CelestialSayuki** [comment]
I got COVID-19, and now I am sick at my grandmother's home. I will test the it as soon as I get my laptop. CC @lietxia

**Review by CelestialSayuki — APPROVED** [review]

**Comment by CelestialSayuki** [comment]
Tested, thanks for your work!

**Comment by CelestialSayuki** [comment]
Well, I think voltageshift is a great work as I can undervolt this CPU without modifying bios, I’ll search more information about it.

**Comment by mandresve** [comment]
> Well, I think voltageshift is a great work as I can undervolt this CPU without modifying bios, I’ll search more information about it.

It's a great tool. Currently, I was able to undervolt i7-10510U -120 mV to CPU, -100 mV to GPU and -70mV CPU Cache without stability compromise plus temp & battery life boost :) all-win scenario.

Captura de pantalla 2023-04-17 a la(s) 2 50 03 a m

**Comment by CelestialSayuki** [comment]
> > Well, I think voltageshift is a great work as I can undervolt this CPU without modifying bios, I’ll search more information about it.
> 
> It's a great tool. Currently, I was able to undervolt i7-10510U -100 mV to CPU, -100 mV to GPU and -70mV CPU Cache without stability compromise plus temp & battery life boost :) all-win scenario.
> 
> Captura de pantalla 2023-04-17 a la(s) 2 50 03 a m

I used to undervolt in BIOS “Advanced-Overclocking Menu”. However, this method is risky and may not boot. In macOS, I can undervolt -65mV to CPU, -85mV to GPU. But windows crashes all the time.

**Comment by CelestialSayuki** [comment]
Interestingly, I found 10510U may have a huge difference in default voltage. XiaoxinAir14 needs 0.75V for idle @1.8GHz in windows, on the contrary, XiaomiBook Pro just need 0.52V.
This can’t assess how much can those laptops undervolt, but Xiaoxin’s cpu seems more energy inefficient all the time.

**Comment by mandresve** [comment]
> Interestingly, I found 10510U may have a huge difference in default voltage. XiaoxinAir14 needs 0.75V for idle @1.8GHz in windows, on the contrary, XiaomiBook Pro just need 0.52V.
> This can’t assess how much can those laptops undervolt, but Xiaoxin’s cpu seems more energy inefficient all the time.

Wow, it's a huge difference. I do not use Windows at all so IDK the 10510U behavior under it, but using Arch Linux, I was able to underclock to 500MHz idle & undervolt CPU -90mV using intel_undervolt package.

**Comment by CelestialSayuki** [comment]
It seems my 10510U on Xiaoxin have a severe problem, it even can’t boot with 0.6V voltage.
As for windows, it’s just a bug after 20H2, but I think damn Microsoft will never fix it.

**Comment by mandresve** [comment]
Just for curiosity. Under your XiaoXin laptop, in the BIOS menu (unlocked advanced settings), under the "Main" tab, your processor SKU is reported as "CML PCH-LP (U) Premium"? Which version of CPU Microcode are you using? (Mine 0xF0)

**Comment by CelestialSayuki** [comment]
> Just for curiosity. Under your XiaoXin laptop, in the BIOS menu (unlocked advanced settings), under the "Main" tab, your processor SKU is reported as "CML PCH-LP (U) Premium"? Which version of CPU Microcode are you using? (Mine 0xF0)

Well, I didn’t notice that, my laptop is not with me, I‘ll check it later.
For some information about how we got it displayed, you can see /BIOS_UnlockOCPM

**Comment by mandresve** [comment]
> > Just for curiosity. Under your XiaoXin laptop, in the BIOS menu (unlocked advanced settings), under the "Main" tab, your processor SKU is reported as "CML PCH-LP (U) Premium"? Which version of CPU Microcode are you using? (Mine 0xF0)
> 
> Well, I didn’t notice that, my laptop is not with me, I‘ll check it later. For some information about how we got it displayed, you can see /BIOS_UnlockOCPM

Let me know as soon as you can. Unfortunately, the "Main" tab is not captured 🥲. But I have a feeling that the CPU microcode is slightly different in our processors, or the quality of the die itself. I'll go to bed, it's 3:30 am here.

**Comment by CelestialSayuki** [comment]
IMG_0011
Here it is, I found it in my video recorded last year.

**Comment by mandresve** [comment]
> IMG_0011 Here it is, I found it in my video recorded last year.

Great. The SKU model is the same, but the bios and microcode revision it's not. In my case, bios rev is CKCN19WW, microcode 0xF0 (i think that the last microcode rev is 0xF1 according to Intel). Maybe there is a substantial difference in power management under the new microcode.

**Comment by CelestialSayuki** [comment]
> > IMG_0011 Here it is, I found it in my video recorded last year.
> 
> Great. The SKU model is the same, but the bios and microcode revision it's not. In my case, bios rev is CKCN19WW, microcode 0xF0 (i think that the last microcode rev is 0xF1 according to Intel). Maybe there is a substantial difference in power management under the new microcode.

I took that picture last year and it‘s the same now

**Comment by mandresve** [comment]
Then we need to test further 2 things: O2 Card Reader & Voltageshift performance differences.

**Comment by CelestialSayuki** [comment]
> Then we need to test further 2 things: O2 Card Reader & Voltageshift performance differences.

After turning on CPUFriend, low power mode is broken

**Comment by mandresve** [comment]
> > Then we need to test further 2 things: O2 Card Reader & Voltageshift performance differences.
> 
> After turning on CPUFriend, low power mode is broken

Can you elaborate on this please?

**Comment by CelestialSayuki** [comment]
Before I use CPUFriend, the cpu will run at a no more than 2.4GHz speed when opening low power mode in macOS. After enabling it, if I enable low power mode, the cpu continues to run at 4.9GHz

**Comment by mandresve** [comment]
> Before I use CPUFriend, the cpu will run at a no more than 2.4GHz speed when opening low power mode in macOS. After enabling it, if I enable low power mode, the cpu continues to run at 4.9GHz

By default, CPUFriend is loaded but no data module is active. Did you loaded the low power profile 10510U data provider kext?

**Comment by CelestialSayuki** [comment]
I loaded the performance one. Both two were generated in Big Sur, should I re-generate them in Monterey?

**Comment by mandresve** [comment]
> I loaded the performance one. Both two were generated in Big Sur, should I re-generate them in Monterey?

Ummm, I was using the power efficient one. I haven't tested it with the performance one. Try to generate another one with cpufriendfriend and If you want, I can test It too.

**Comment by mandresve** [comment]
> I loaded the performance one. Both two were generated in Big Sur, should I re-generate them in Monterey?

I generated new CPUFriendDataProvider Kexts ranging from 0 - Max Powersave to 6- Max performance. I test out them in my machine and are working as expected. If you can conduct more exhaustive test, I'll thank to you. 

If everything is OK, I'll consider to merge this settings in another merge request.

[CPUFriendDataProviders 10510U.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/11276604/CPUFriendDataProviders.10510U.zip)

**Pull request merged**
